template-file-path: template.yaml
parameters:
    imageId: /aws/service/ami-windows-latest/Windows_Server-2025-English-Full-Base
    ec2Name: Windows Server-GAMING
    instanceType: g5.2xlarge
    vpcID: vpc-0e2e3c1e037409daa
    subnetID: subnet-0d2b9b0cbc67ba6f1
    displayPublicIP: "Yes"
    assignStaticIP: "No"
    ingressIPv4: 0.0.0.0/32
    volumeSize: 250
    volumeType: "gp3"
tags: {}
